config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in'  => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'

  root :to => 'sessions#new'

  resources :users
  resources :sessions
  resources :posts
  resources :widgets
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :author, presence: true
	validates :description, presence: true
	validates_length_of :description, :maximum => 500
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation
	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else 
			nil
		end	
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end	
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post }
      else
        format.html { redirect_to @post }
        format.json { render json: @post.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callback
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:author, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to posts_url, :notice => "Logged in!"	
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
  	end	
  end
  
  def destroy
	session[:user_id] = nil
	redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to root_url, :notice => "Signed Up!"
  	else
  		render  "new"
  	end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miniblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<div id="user_nav">
	<% if current_user %>
		Logged in as <%= current_user.email %>
		<%= link_to "Log out", log_out_path %>
	<% else %>		
		<%= link_to "Sign up", sign_up_path %>
		<%= link_to "Log in", log_in_path %>
	<% end %>	
</div>

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="page-header">
  <h1>Mini Blog Rails</h1>
</div>
<div style="overflow-y:scroll; overflow-x:hidden; width:600px; height: 300px;">
  <div id="listPosts">
    <% @posts.each do |post| %>
      <p>
          <%= post.description %><br/>
          <%= post.author %>
      </p> 
    <% end %>
  </div>
</div>
<div>
  <div>
    <%= form_for(@post, remote: true, format: :json, html: {class: :post_form}) do |f| %>

      <div id="error_explanation" style='display:none;'>
        <ul>
          <% if @post.errors.any? %>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="field">
        <%= label_tag(:author,"Autor:") %>
        <%= f.text_field :author %>
        <%= label_tag(:description,"Descrição:") %>
        <%= f.text_area :description %>
      </div>
      <div class="actions">
        <%= f.submit "Enviar Postagem" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages%>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>	
	<% end %>
	
	<p>
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</p>
	
	<p>
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</p>
	
	<p>
		<%= f.label :password_confirmation %> <br />
		<%= f.password_field :password_confirmation %>
	</p>

	<p class="button"> <%= f.submit %> </p>
<% end %>